[package]
name = "terminal_clock"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.22"
clap = { version = "4.0.10", features = [ "derive" ]}
no-panic = "0.1.16"
termion = "1.5.6"